server:
  port: 8082

service:
  input-data-path: classpath:static/Prices
  crypto:
    supported-currencies:
      - BTC
      - DOGE
      - ETH
      - LTC
      - XRP
  scheduling:
    enabled: true
#    cron: "0 5 0 * * *" #every day at 12:05 AM
    cron: "*/20 * * * * *" #every 20 seconds
    timezone: "GMT"
spring:
  datasource:
    url: jdbc:h2:mem:cryptos
    #    url: jdbc:h2:file:~/cryptos.db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        jdbc:
          batch_size: 15
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        generate_statistics: false
        format_sql: true
        hbm2ddl:
          auto: update
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: false
springdoc:
  swagger-ui:
    operations-sorter: method