server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:cryptos
    #    url: jdbc:h2:file:~/cryptos.db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        jdbc:
          batch_size: 15
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        generate_statistics: true
        format_sql: true
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: false
